language: ruby
cache: bundler
rvm:
- 2.2.7
sudo: false
script:
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  bundle exec rake deploy ; fi ;
- if [[ $TRAVIS_PULL_REQUEST == "true" ]]; then jekyll build ; fi ;
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
env:
  global:
    secure: r96RtJmKJwSP4A2GsN9/avcqgzUZk4JtUyvurdfiAWvvy6QG/2aGoXO9vKfNX05kvJO6a5D4GJqJV/9fqWrJZlYVMKUJN/a6Q3Bxd/QjeerV33Mm7FTzp/Gcqlf+P9pv12xed3nKz1Ia/F+mESrGQ/9a1T+1KXZkXMJqhnxxeI3rp2j7X0rS5+SqAizkwffw7Qlr+w3q3UrX/iEr+ZmsKeuMOnng8L3Ap8ujVtxtug9cPxzyURs7EW/Oi/sm/7wv0XSY9Gp8lNvGHg02QoTPTdrt4JSlO1xgdXBVNAgicDtGvZHCfbQbZ94Jk9QF/qn1z9a/PFLyWkAG94Oi/f9fJH+q0mzB2ESh8uSOnE07XPrhbiM/4kptKZySuT4jx3kGZRoB5NAZA2vEB/uH9vXJy2TVYycn+u7F8+YhrS1imdS2dl/Wzrtj2X6ToPYqJgbhWJr7YRSGwv15oriUM3q8Csd5/zm1fOUAGk2GyOx8z6h+4i4FczD3T7jPaf8qtubdFxLTogfS0AvndQzNE1PH6C2l2fjSt5ZTuP5ODQTj4kyD2xETGtOKW50LviR5QTOqpODYRbiEcY8uts9EUG5wtKIemK7hPx3StD7SpRIhihkxeTtujlzxDKA20aeyq14zwhXkJcpAGafgdc0mhGasNBK8w5qLH3uXoyyT2XkmqP4=
