language: ruby
cache: bundler
rvm:
- 2.2.7
sudo: false
script:
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  bundle exec rake deploy ; fi ;
- if [[ $TRAVIS_PULL_REQUEST == "true" ]]; then jekyll build ; fi ;
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
env:
  global:
    secure: pP7zC7yVrcU5VNOQ7nrj9pUI/kUGs26AGHSkVCkZViqUSAbnsZO63ns92LLd+teUm9bMZ20uSM9e+3R5XTqOrEnbQVt4iZT5XiGZOCncveeYAae45/AyzLYI+mjxH2xi9k1zvGwS419E6DnyrwKk94QNx6gpl8ufjSaah3+UnX5APnno9Ka5jAuQpGpd0gS+00bNMLly3SNrifr/V2jv5UCMD0iAnQ5LHl+65foVf0LqRFRmFGrsRxxJZgXBHack50gJ7Kv6DgM9djP9N9po8EnsccsXHEd4hpWQ9LEEEnHFxKCXZ9Bm/BNCUhbOAWnNP+J+K+8aefOurk1sX95pJLm7eq6aUvuR/jiXg7FsotGL5XUDehHQfL1xFSpLqZphblYZCXPicY3kzLMl1CWxolit73TWsUjk4vCBfboHTi2HNG1hyT6zjFbPoCvLZsvJTJlaCX6gXaPr47kbUuzEjTwDGiyysx47YZPxmU8lJeS3WbbgbAa6GtD53xg+m2DuiejdlYsXw1N/ukbaY+eKA7V/hZodRCTcRSwfKYMNDMk03MiqB3CrpwGCa2/gifXNlSRIOuiE70dAbCiDrQVpiOqe6PSUCQLoEMSBU9ZVKM0AKeUVArDiXZSLNNnmo21DT8So/YnI2a/n6Bpy5Y/DBZsThz8rsYZU7jh607fQOf4=
